<x-app-layout>
    <div>
        <livewire:basic-banner/>
        <livewire:breadcrumb/>
        <livewire:single-featured-news-list/>
        <livewire:featured-news/>
        <livewire:footer/>
    </div>
</x-app-layout>
