<x-app-layout>
    <div>
        <livewire:banner/>
        <livewire:breadcrumb/>
        <livewire:single-gallery-list/>
        <livewire:latest-gallery/>
        <livewire:footer/>
    </div>
</x-app-layout>